version: "3.9"

services:
  comfyui:
    build: .
    container_name: comfyui
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - models:/ComfyUI/models
      - input:/ComfyUI/input
      - output:/ComfyUI/output
      - custom_nodes:/ComfyUI/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  input:
  output:
  models:
  custom_nodes:
